# Training Config
# -----------------
dataset: coco # 대회 데이터셋 형식인 coco
model: tf_efficientdet_d4 # 사용할 모델 지정
redundant_bias: null
soft_nms: null
val_skip: 0
num-classes: 10
pretrained: true
no_pretrained_backbone: false
initial_checkpoint: '/path/to/pretrained.pth' # pretrained 사용시 pth 파일의 path 지정
resume: ''
no_resume_opt: false
mean:
  - 0.485
  - 0.456
  - 0.406
std:
  - 0.229
  - 0.224
  - 0.225
interpolation: ''
fill_color: null
batch_size: 3
clip_grad: 5.0
clip_mode: norm

# Optimizer parameters
# ---------------------
opt: adamw
opt_eps: 0.001
momentum: 0.9
weight_decay: 4.0e-05

# Learning rate schedule parameters
# ---------------------------------
lr_scheduler: cosine
lr: 1.0e-04
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
lr_cycle_mul: 1.0
lr_cycle_limit: 1
warmup_lr: 1.0e-05
min_lr: 1.0e-05
epochs: 20
start_epoch: null
decay_epochs: 20
warmup_epochs: 2
cooldown_epochs: 3
patience_epochs: 4
decay_rate: 0.2

# Augmentation parameters
# ------------------------
color_jitter: 0.4
aa: original
reprob: 0.0
remode: pixel
recount: 2
train_interpolation: random

# Loss
# ----
smoothing: null
jit_loss: null
legacy_focal: null

# Model Exponential Moving Average
# --------------------------------
model_ema: false
model_ema_decay: 0.9998

# Misc
# ----
sync_bn: false
dist_bn: ''
seed: 42
log_interval: 50
recovery_interval: 0
workers: 4
save_images: false
amp: false
apex_amp: false
native_amp: false
channels_last: false
pin_mem: false
no_prefetcher: false
torchscript: false
bench_labeler: false
output: /path/to/output # 결과사항 저장될 path 지정
eval_metric: map
tta: 0
local_rank: 0
